// <auto-generated />
using System;
using DotaStat.Data.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DotaStat.Data.EntityFramework.Migrations
{
    [DbContext(typeof(DotaStatDbContext))]
    [Migration("20211031002308_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DataBase.Model.Item", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("DotaStat.Data.EntityFramework.Model.CurrentWinrateAlly", b =>
                {
                    b.Property<byte>("MainHero")
                        .HasColumnType("tinyint");

                    b.Property<byte>("ComparedHero")
                        .HasColumnType("tinyint");

                    b.Property<int>("LosesOfMain")
                        .HasColumnType("int");

                    b.Property<int>("WeekPatchId")
                        .HasColumnType("int");

                    b.Property<int>("WinsOfMain")
                        .HasColumnType("int");

                    b.HasKey("MainHero", "ComparedHero");

                    b.HasIndex("ComparedHero");

                    b.HasIndex("WeekPatchId");

                    b.ToTable("CurrentWinrateAllies");
                });

            modelBuilder.Entity("DotaStat.Data.EntityFramework.Model.CurrentWinrateEnemy", b =>
                {
                    b.Property<byte>("MainHero")
                        .HasColumnType("tinyint");

                    b.Property<byte>("ComparedHero")
                        .HasColumnType("tinyint");

                    b.Property<int>("LosesOfMain")
                        .HasColumnType("int");

                    b.Property<int>("WeekPatchId")
                        .HasColumnType("int");

                    b.Property<int>("WinsOfMain")
                        .HasColumnType("int");

                    b.HasKey("MainHero", "ComparedHero");

                    b.HasIndex("ComparedHero");

                    b.HasIndex("WeekPatchId");

                    b.ToTable("CurrentWinrateEnemies");
                });

            modelBuilder.Entity("DotaStat.Data.EntityFramework.Model.Hero", b =>
                {
                    b.Property<byte>("Id")
                        .HasColumnType("tinyint");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Heroes");
                });

            modelBuilder.Entity("DotaStat.Data.EntityFramework.Model.User", b =>
                {
                    b.Property<long>("SteamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("MyProperty")
                        .HasColumnType("datetime2");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("SteamId");

                    b.HasIndex("Role");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DotaStat.Data.EntityFramework.Model.UserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("DotaStat.Data.EntityFramework.Model.WeekPatch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Patch")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WeekId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("WeekPatches");
                });

            modelBuilder.Entity("DotaStat.Data.EntityFramework.Model.WeeklyWinrate", b =>
                {
                    b.Property<int>("WeekPatchId")
                        .HasColumnType("int");

                    b.Property<byte>("HeroId")
                        .HasColumnType("tinyint");

                    b.Property<int>("AllGames")
                        .HasColumnType("int");

                    b.Property<int>("Wins")
                        .HasColumnType("int");

                    b.HasKey("WeekPatchId", "HeroId");

                    b.HasIndex("HeroId");

                    b.ToTable("WeeklyHeroWinRates");
                });

            modelBuilder.Entity("DotaStat.Data.EntityFramework.Model.CurrentWinrateAlly", b =>
                {
                    b.HasOne("DotaStat.Data.EntityFramework.Model.Hero", "HeroCompareWith")
                        .WithMany("CurrentWinrateAlliesCompared")
                        .HasForeignKey("ComparedHero")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DotaStat.Data.EntityFramework.Model.Hero", "HeroMain")
                        .WithMany("CurrentWinrateAlliesMain")
                        .HasForeignKey("MainHero")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DotaStat.Data.EntityFramework.Model.WeekPatch", "WeekPatch")
                        .WithMany("LastWeekHeroWinRates")
                        .HasForeignKey("WeekPatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HeroCompareWith");

                    b.Navigation("HeroMain");

                    b.Navigation("WeekPatch");
                });

            modelBuilder.Entity("DotaStat.Data.EntityFramework.Model.CurrentWinrateEnemy", b =>
                {
                    b.HasOne("DotaStat.Data.EntityFramework.Model.Hero", "HeroCompareWith")
                        .WithMany("CurrentWinrateEnemiesCompared")
                        .HasForeignKey("ComparedHero")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DotaStat.Data.EntityFramework.Model.Hero", "HeroMain")
                        .WithMany("CurrentWinrateEnemiesMain")
                        .HasForeignKey("MainHero")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DotaStat.Data.EntityFramework.Model.WeekPatch", "WeekPatch")
                        .WithMany()
                        .HasForeignKey("WeekPatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HeroCompareWith");

                    b.Navigation("HeroMain");

                    b.Navigation("WeekPatch");
                });

            modelBuilder.Entity("DotaStat.Data.EntityFramework.Model.User", b =>
                {
                    b.HasOne("DotaStat.Data.EntityFramework.Model.UserRole", "UserRole")
                        .WithMany("Users")
                        .HasForeignKey("Role")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserRole");
                });

            modelBuilder.Entity("DotaStat.Data.EntityFramework.Model.WeeklyWinrate", b =>
                {
                    b.HasOne("DotaStat.Data.EntityFramework.Model.Hero", "Hero")
                        .WithMany("WeeklyHeroWinRates")
                        .HasForeignKey("HeroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DotaStat.Data.EntityFramework.Model.WeekPatch", "WeekPatch")
                        .WithMany("WeeklyHeroWinRates")
                        .HasForeignKey("WeekPatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hero");

                    b.Navigation("WeekPatch");
                });

            modelBuilder.Entity("DotaStat.Data.EntityFramework.Model.Hero", b =>
                {
                    b.Navigation("CurrentWinrateAlliesCompared");

                    b.Navigation("CurrentWinrateAlliesMain");

                    b.Navigation("CurrentWinrateEnemiesCompared");

                    b.Navigation("CurrentWinrateEnemiesMain");

                    b.Navigation("WeeklyHeroWinRates");
                });

            modelBuilder.Entity("DotaStat.Data.EntityFramework.Model.UserRole", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("DotaStat.Data.EntityFramework.Model.WeekPatch", b =>
                {
                    b.Navigation("LastWeekHeroWinRates");

                    b.Navigation("WeeklyHeroWinRates");
                });
#pragma warning restore 612, 618
        }
    }
}
